apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - '**'

inputs:
  pathtobinary:  
  description: 'Path to binary'
  required: true
    
jobs:
  Run_Main_Job:
    outputs:
      jenkins_output:
    steps:
      - name: Create file
        id: step3
        uses: docker://curlimages/curl:latest
        shell: sh
        run: |
          echo "This is an example file - $(date)" > ${{inputs.pathtobinary}}
          echo ${{inputs.pathtobinary}} > ${{outputs.jenkins_output}}
          
      - name: Print file
        id: step3
        uses: docker://curlimages/curl:latest
        shell: sh
        run: echo ${{outputs.jenkins_output}}

