apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
inputs:
  pathtobinary:  
    description: 'Path to binary'
    required: true
    
on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
