apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      pathtobinary:
        type: string
        default: example.txt
        required: true
      artifactversion:
        type: string
        default: 1.0.0
        required: true
jobs:
  build:
    outputs:
      outfile:
        type: string
        default: example2.txt
        required: true
    steps:
      - name: Create file
        id: step1
        uses: docker://curlimages/curl:latest
        shell: sh
        run: |
          echo "This is an example file - $(date)" > ${{inputs.pathtobinary}}
          echo ${{inputs.pathtobinary}} > ${{inputs.pathtobinary}} 
          echo ${{inputs.pathtobinary}} 

